### ISSUE TITLE
Vanilla Spawner Crash

### ISSUE THREAD

**Issue by EndermanParty** [TehNut-Mods/Soul-Shards-The-Old-Ways#4] opened 2016-03-05 21:44 UTC
I right clicked a soul shard that had a single wither skeleton kill in it on a Spider Spawner and it gave me this crash.
http://paste.ee/p/QZGtH

**Comment by EndermanParty** [comment] 2016-03-05 21:45
If needed the spider spawner was one from Rougelike Dungeon.

**Comment by TehNut** [comment] 2016-03-05 22:21
Dupe of #3 

Please update to the latest version. I fixed this yesterday.

**Closed as completed by TehNut** 2016-03-05 22:21 UTC
Labels: duplicate

**Comment by EndermanParty** [comment] 2016-03-06 18:32
Alrighty thanks.
